apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: dev
---
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJjY3IuY2NzLnRlbmNlbnR5dW4uY29tIjogewoJCQkiYXV0aCI6ICJNVEF3TURJME5UUXdNRE16T2sxaU9ETXlNREV3TkRnPSIKCQl9Cgl9Cn0=
kind: Secret
metadata:
  creationTimestamp: "2022-07-14T08:39:11Z"
  name: dev-key
  namespace: dev
  resourceVersion: "227236"
  uid: 0c985228-7705-4019-9438-05b4fdee0179
type: kubernetes.io/dockerconfigjson
