apiVersion: v1
kind: Service
metadata:
  name: violin-bookmark-service-prod
  namespace: devops
spec:
  selector:
    app: violin-bookmark
  # type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
