kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: violin-docs-pvc-stage
  namespace: stage
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi